apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "control-plane:latest"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"control-plane\")].image"
        }
      ]
