apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-provider-config
data:
  LLM_ENDPOINT: http://ims-generative-proxy.ims-datascience.svc.cluster.local
  LLM_MODEL: llama-32-3b-instruct
  LLM_REQUEST_TIMEOUT_SECONDS: "20"
