apiVersion: v1
kind: Secret
metadata:
  name: model-storage-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: ani-models
  AWS_S3_ENDPOINT: http://model-storage-minio.ani-data.svc.cluster.local:9000
  AWS_SECRET_ACCESS_KEY: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ROOT_USER: minioadmin
  type: s3
