apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ims-tekton-image-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ims-tekton
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ims-data-image-puller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
  - kind: Group
    name: system:serviceaccounts:ims-data
