apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ims-demo-argocd-image-registry-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - configs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ims-demo-argocd-image-registry-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ims-demo-argocd-image-registry-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
