apiVersion: batch/v1
kind: CronJob
metadata:
  name: sipp-normal-traffic
  namespace: ims-demo-lab
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sipp
              image: sipp-runner:latest
              workingDir: /tmp
              command:
                - /bin/sh
                - -c
              args:
                - >
                  sipp ims-pcscf.ims-demo-lab.svc.cluster.local:5060
                  -sf /scenarios/register-normal.xml
                  -m 50
                  -r 2
              volumeMounts:
                - name: scenarios
                  mountPath: /scenarios
          volumes:
            - name: scenarios
              configMap:
                name: sipp-scenarios
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sipp-registration-storm
  namespace: ims-demo-lab
spec:
  schedule: "*/30 * * * *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sipp
              image: sipp-runner:latest
              workingDir: /tmp
              command:
                - /bin/sh
                - -c
              args:
                - >
                  sipp ims-pcscf.ims-demo-lab.svc.cluster.local:5060
                  -sf /scenarios/register-storm.xml
                  -m 400
                  -r 20
              volumeMounts:
                - name: scenarios
                  mountPath: /scenarios
          volumes:
            - name: scenarios
              configMap:
                name: sipp-scenarios
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sipp-malformed-invite
  namespace: ims-demo-lab
spec:
  schedule: "*/30 * * * *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sipp
              image: sipp-runner:latest
              workingDir: /tmp
              command:
                - /bin/sh
                - -c
              args:
                - >
                  sipp ims-pcscf.ims-demo-lab.svc.cluster.local:5060
                  -sf /scenarios/invite-malformed.xml
                  -m 80
                  -r 8
              volumeMounts:
                - name: scenarios
                  mountPath: /scenarios
          volumes:
            - name: scenarios
              configMap:
                name: sipp-scenarios
