apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/namespaces.yaml
  - rbac/argocd-image-registry.yaml
  - configs/image-registry.yaml
  - configs/node-feature-discovery.yaml
  - configs/gpu-cluster-policy.yaml
  - operatorgroups/grafana-operator.yaml
  - operatorgroups/redhat-ods-operator.yaml
  - operatorgroups/openshift-nfd.yaml
  - operatorgroups/nvidia-gpu-operator.yaml
  - operatorgroups/openshift-serverless.yaml
  - operatorgroups/ansible-automation-platform.yaml
  - subscriptions/grafana-operator.yaml
  - subscriptions/rhoai.yaml
  - subscriptions/nfd.yaml
  - subscriptions/gpu-operator.yaml
  - subscriptions/service-mesh.yaml
  - subscriptions/pipelines.yaml
  - subscriptions/serverless.yaml
  - subscriptions/authorino.yaml
  - subscriptions/ansible-automation-platform.yaml
  - subscriptions/amq-streams.yaml
