apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plane-rendered.yaml
  - routes.yaml
patches:
  - path: patch-plane-app-vars.yaml
  - path: patch-plane-web-nginx.yaml
  - path: patch-plane-admin-nginx.yaml
  - path: patch-plane-worker-command.yaml
