apiVersion: v1
kind: Secret
metadata:
  name: dspa-object-storage
  namespace: ani-demo-lab
  annotations:
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: ani-demo-lab
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  dspVersion: v2
  apiServer:
    enableSamplePipeline: false
    pipelineStore: kubernetes
  objectStorage:
    externalStorage:
      scheme: http
      host: model-storage-minio.ani-data.svc.cluster.local
      port: "9000"
      bucket: ani-models
      basePath: pipelines/ani-datascience
      secure: false
      s3CredentialsSecret:
        secretName: dspa-object-storage
        accessKey: accesskey
        secretKey: secretkey
  database:
    mariaDB:
      pvcSize: 10Gi
