apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: ani-kfp-assets
    files:
      - ani_anomaly_pipeline.yaml=assets/ani_anomaly_pipeline.yaml
      - publish_pipeline.py=assets/publish_pipeline.py
  - name: ani-feature-bundle-kfp-assets
    files:
      - ani_feature_bundle_pipeline.yaml=assets/ani_feature_bundle_pipeline.yaml
      - publish_feature_bundle_pipeline.py=assets/publish_feature_bundle_pipeline.py
  - name: ani-featurestore-kfp-assets
    files:
      - ani_featurestore_pipeline.yaml=assets/ani_featurestore_pipeline.yaml
      - publish_featurestore_pipeline.py=assets/publish_featurestore_pipeline.py
  - name: ani-incident-release-kfp-assets
    files:
      - ani_incident_release_pipeline.yaml=assets/ani_incident_release_pipeline.yaml
      - publish_incident_release_pipeline.py=assets/publish_incident_release_pipeline.py
generatorOptions:
  disableNameSuffixHash: true
resources:
  - dspa.yaml
  - bootstrap-rbac.yaml
  - pipeline-anomaly.yaml
  - pipeline-feature-bundle.yaml
  - pipeline-featurestore.yaml
  - pipeline-incident-release.yaml
  - pipeline-auto-runs.yaml
