FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends sipp ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

ENTRYPOINT ["/usr/bin/sipp"]
