apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    strimzi.io/cluster: ani-release-kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  jvmOptions:
    "-Xms": 512m
    "-Xmx": 1G
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
