apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ani-incidents-bronze
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  labels:
    strimzi.io/cluster: ani-release-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ani-feature-windows-bronze
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  labels:
    strimzi.io/cluster: ani-release-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ani-release-artifacts
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  labels:
    strimzi.io/cluster: ani-release-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: aiops-ansible-playbook-generate-instruction
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  labels:
    strimzi.io/cluster: ani-release-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
