apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-minio
  namespace: ims-demo-lab
  annotations:
    opendatahub.io/connection-type-protocol: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: minio
    serving.kserve.io/s3-endpoint: model-storage-minio.ims-demo-lab.svc.cluster.local:9000
    serving.kserve.io/s3-region: us-east-1
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-usevirtualbucket: "0"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: ims-models
  AWS_S3_ENDPOINT: http://model-storage-minio.ims-demo-lab.svc.cluster.local:9000
