apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-connection-minio.yaml
  - serving.yaml
  - autogluon-mlserver-runtime.yaml
  - llm-serving.yaml
  - featurestore-serving.yaml
  - featurestore-serving-backfill-modelcar.yaml
  - triton-template-rbac.yaml
  - triton-runtime-template.yaml
