apiVersion: v1
kind: ConfigMap
metadata:
  name: ani-featurestore-config
  namespace: ani-demo-lab
data:
  FEATURESTORE_INSTANCE_NAME: ani-featurestore
  FEATURESTORE_BOOTSTRAP_CRONJOB_NAME: feast-ani-featurestore
  FEATURE_STORE_PROJECT: ani_anomaly_featurestore
  FEATURE_STORE_REPO_PATH: /workspace/ai/featurestore/feature_repo
  FEATURE_BUNDLE_ROOT_URI: s3://ani-models/pipelines/ani-datascience/datasets/feature-bundles/
  FEATURESTORE_OFFLINE_SOURCE_PATH: s3://ani-models/pipelines/ani-datascience/datasets/feature-bundles/ani-feature-bundle-v1/feature_store/offline_source.parquet
  FEATURESTORE_LABEL_SOURCE_PATH: s3://ani-models/pipelines/ani-datascience/datasets/feature-bundles/ani-feature-bundle-v1/parquet/window_labels.parquet
  FEATURESTORE_SERVING_ROOT_URI: s3://ani-models/predictive-featurestore/ani-predictive-fs/current/
