apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-featurestore-config
  namespace: ims-demo-lab
data:
  FEATURESTORE_INSTANCE_NAME: ims-featurestore
  FEATURESTORE_BOOTSTRAP_CRONJOB_NAME: feast-ims-featurestore
  FEATURE_STORE_PROJECT: ims_anomaly_featurestore
  FEATURE_STORE_REPO_PATH: /workspace/ai/featurestore/feature_repo
  FEATURE_BUNDLE_ROOT_URI: s3://ims-models/pipelines/ims-demo-lab/datasets/feature-bundles/
  FEATURESTORE_OFFLINE_SOURCE_PATH: s3://ims-models/pipelines/ims-demo-lab/datasets/feature-bundles/ims-feature-bundle-v1/feature_store/offline_source.parquet
  FEATURESTORE_LABEL_SOURCE_PATH: s3://ims-models/pipelines/ims-demo-lab/datasets/feature-bundles/ims-feature-bundle-v1/parquet/window_labels.parquet
  FEATURESTORE_REGISTRY_PATH: feast-ims-featurestore-registry.ims-demo-lab.svc.cluster.local:443
  FEATURESTORE_ONLINE_STORE_PATH: https://feast-ims-featurestore-online.ims-demo-lab.svc.cluster.local:443
  FEATURESTORE_CA_CERT_PATH: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  FEAST_S3_ENDPOINT_URL: http://model-storage-minio.ims-demo-lab.svc.cluster.local:9000
  FEATURESTORE_SERVING_ROOT_URI: s3://ims-models/predictive-featurestore/ims-predictive-fs/current/
  CONTROL_PLANE_URL: http://control-plane.ims-demo-lab.svc.cluster.local:8080
  MODEL_REGISTRY_ENDPOINT: http://ims-demo-modelregistry.rhoai-model-registries.svc.cluster.local:8080
