apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ims-demo-container-build
  namespace: ims-demo-lab
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image
      type: string
    - name: context-dir
      type: string
    - name: dockerfile
      type: string
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: namespace
            value: openshift-pipelines
          - name: name
            value: git-clone
      params:
        - name: URL
          value: $(params.git-url)
        - name: REVISION
          value: $(params.git-revision)
        - name: DELETE_EXISTING
          value: "true"
      workspaces:
        - name: output
          workspace: source
    - name: build
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: namespace
            value: openshift-pipelines
          - name: name
            value: buildah
      params:
        - name: IMAGE
          value: $(params.image)
        - name: CONTEXT
          value: $(params.context-dir)
        - name: DOCKERFILE
          value: $(params.dockerfile)
      workspaces:
        - name: source
          workspace: source
