apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: ims-demo-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-edit
  namespace: ims-demo-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ims-demo-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-pipelines-scc
  namespace: ims-demo-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:pipelines-scc
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ims-demo-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-image-builder
  namespace: ims-demo-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ims-demo-lab
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sipp-runner
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: feature-gateway
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-service
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rca-service
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: demo-ui
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: control-plane
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ims-ai-trainer
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ims-ai-featurestore-trainer
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ims-incident-release
  namespace: ims-demo-lab
spec:
  lookupPolicy:
    local: false
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ims-demo-gitea-binding
  namespace: ims-demo-lab
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ims-demo-gitea-template
  namespace: ims-demo-lab
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ims-demo-build-
        namespace: ims-demo-lab
      spec:
        pipelineRef:
          name: ims-demo-container-build
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 4h0m0s
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ims-demo-gitea
  namespace: ims-demo-lab
spec:
  serviceAccountName: pipeline
  namespaceSelector: {}
  resources: {}
  triggers:
    - name: main-branch-commit
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: cel
          params:
            - name: filter
              value: header.match('X-Gitea-Event', 'push') && body.ref == 'refs/heads/main'
      bindings:
        - kind: TriggerBinding
          ref: ims-demo-gitea-binding
      template:
        ref: ims-demo-gitea-template
