apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ims-feature-gateway-build
  annotations:
    chains.tekton.dev/signed: "true"
  namespace: ims-demo-lab
spec:
  pipelineRef:
    name: ims-demo-container-build
  params:
    - name: git-url
      value: https://github.com/pandeybk/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/feature-gateway:latest
    - name: context-dir
      value: .
    - name: dockerfile
      value: services/feature-gateway/Containerfile
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ims-anomaly-service-build
  annotations:
    chains.tekton.dev/signed: "true"
  namespace: ims-demo-lab
spec:
  pipelineRef:
    name: ims-demo-container-build
  params:
    - name: git-url
      value: https://github.com/pandeybk/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/anomaly-service:latest
    - name: context-dir
      value: .
    - name: dockerfile
      value: services/anomaly-service/Containerfile
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ims-rca-service-build
  annotations:
    chains.tekton.dev/signed: "true"
  namespace: ims-demo-lab
spec:
  pipelineRef:
    name: ims-demo-container-build
  params:
    - name: git-url
      value: https://github.com/pandeybk/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/rca-service:latest
    - name: context-dir
      value: .
    - name: dockerfile
      value: services/rca-service/Containerfile
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ims-demo-ui-build
  annotations:
    chains.tekton.dev/signed: "true"
  namespace: ims-demo-lab
spec:
  pipelineRef:
    name: ims-demo-container-build
  params:
    - name: git-url
      value: https://github.com/pandeybk/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/demo-ui:latest
    - name: context-dir
      value: .
    - name: dockerfile
      value: services/demo-ui/Containerfile
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ims-control-plane-build
  annotations:
    chains.tekton.dev/signed: "true"
  namespace: ims-demo-lab
spec:
  pipelineRef:
    name: ims-demo-container-build
  params:
    - name: git-url
      value: https://github.com/pandeybk/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/control-plane:latest
    - name: context-dir
      value: .
    - name: dockerfile
      value: services/control-plane/Containerfile
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ims-ai-trainer-build
  annotations:
    chains.tekton.dev/signed: "true"
  namespace: ims-demo-lab
spec:
  pipelineRef:
    name: ims-demo-container-build
  params:
    - name: git-url
      value: https://github.com/pandeybk/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/ims-ai-trainer:latest
    - name: context-dir
      value: .
    - name: dockerfile
      value: ai/training/Containerfile
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
