apiVersion: v2
appVersion: 0.3.0-alpha.5
description: A Helm chart to distribute the project kagenti-operator
icon: https://example.com/icon.png
name: kagenti-operator-chart
type: application
version: 0.3.0-alpha.5
