apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ani-sipp
resources:
  - image-streams.yaml
  - workload-access.yaml
  - ../../../base/builds
  - ../../../base/ims
images:
  - name: image-registry.openshift-image-registry.svc:5000/ani-demo-lab/openimss-open5gs
    newName: quay.io/autonomousnetworkintelligence/openimss-open5gs
    newTag: latest
  - name: image-registry.openshift-image-registry.svc:5000/ani-demo-lab/openimss-opensips
    newName: quay.io/autonomousnetworkintelligence/openimss-opensips
    newTag: latest
