apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ani-tekton-image-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ani-tekton
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aap-scale-ims-scscf
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames: ["ims-scscf"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aap-controller-scale-ims-scscf
subjects:
  - kind: ServiceAccount
    name: aap-controller
    namespace: aap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aap-scale-ims-scscf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aap-remediation-runtime
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["ims-pcscf"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aap-controller-remediation-runtime
subjects:
  - kind: ServiceAccount
    name: aap-controller
    namespace: aap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aap-remediation-runtime
