apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ani-ai-trainer
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ani-ai-featurestore-trainer
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ani-incident-release
spec:
  lookupPolicy:
    local: false
