apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ims-ai-trainer
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ims-ai-featurestore-trainer
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ims-incident-release
spec:
  lookupPolicy:
    local: false
