apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ani-datascience
commonAnnotations:
  argocd.argoproj.io/ignore-healthcheck: "true"
components:
  - ../../../components/image-registry/quay-public-images
resources:
  - ani-platform-config.yaml
  - image-streams.yaml
  - model-storage-credentials.yaml
  - tekton-image-access.yaml
  - ../../../base/kfp
  - ../../../base/feature-store
  - ../../../base/serving
patches:
  - target:
      group: serving.kserve.io
      version: v1alpha1
      kind: ServingRuntime
      name: ani-autogluon-mlserver-runtime
    patch: |-
      - op: replace
        path: /spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/ani-datascience/ani-ai-featurestore-trainer@sha256:370fe9f5d087aa5175a5ae50cd2db98c6d49564611cd58046bec3a2b950502e5
