apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ani-datascience
resources:
  - ani-platform-config.yaml
  - image-streams.yaml
  - model-storage-credentials.yaml
  - tekton-image-access.yaml
  - ../../../base/kfp
  - ../../../base/feature-store
  - ../../../base/serving
