apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ims-datascience
resources:
  - ims-platform-config.yaml
  - image-streams.yaml
  - tekton-image-access.yaml
  - ../../../base/kfp
  - ../../../base/feature-store
  - ../../../base/serving
