apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ani-tekton
components:
  - ../../../components/image-registry/openshift-tekton-build-targets
resources:
  - tasks.yaml
  - tekton-triggering.yaml
  - tekton-pipeline.yaml
  - backfill-modelcar-pipeline.yaml
