apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ani-tekton
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-pipelines-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:pipelines-scc
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ani-tekton
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ani-platform-gitea-binding
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ani-platform-gitea-template
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ani-platform-build-
        namespace: ani-tekton
      spec:
        pipelineRef:
          name: ani-platform-container-build
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 4h0m0s
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ani-platform-gitea
spec:
  serviceAccountName: pipeline
  namespaceSelector: {}
  resources: {}
  triggers:
    - name: repo-push
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: cel
          params:
            - name: filter
              value: header.match('X-Gitea-Event', 'push')
      bindings:
        - kind: TriggerBinding
          ref: ani-platform-gitea-binding
      template:
        ref: ani-platform-gitea-template
