apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ani-platform-container-build
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: publish-to-quay
      type: string
      default: "false"
    - name: quay-image-tag
      type: string
      default: ""
    - name: quay-promote-latest
      type: string
      default: "false"
    - name: quay-organization
      type: string
      default: autonomousnetworkintelligence
  workspaces:
    - name: source
  tasks:
    - name: clone
      retries: 1
      timeout: 15m0s
      taskRef:
        name: git-clone-lite
      params:
        - name: URL
          value: $(params.git-url)
        - name: REVISION
          value: $(params.git-revision)
        - name: DELETE_EXISTING
          value: "true"
      workspaces:
        - name: output
          workspace: source
    - name: build-sipp-runner
      retries: 1
      timeout: 45m0s
      runAfter:
        - clone
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ani-sipp/sipp-runner:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: services/sipp-runner/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-feature-gateway
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-sipp-runner
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ani-runtime/feature-gateway:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: services/feature-gateway/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-anomaly-service
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-feature-gateway
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ani-runtime/anomaly-service:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: services/anomaly-service/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-rca-service
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-anomaly-service
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ani-runtime/rca-service:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: services/rca-service/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-demo-ui
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-rca-service
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ani-runtime/demo-ui:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: services/demo-ui/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-control-plane
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-demo-ui
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ani-runtime/control-plane:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: services/control-plane/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-ani-ai-trainer
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-control-plane
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: quay.io/autonomousnetworkintelligence/ani-ai-trainer:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: ai/training/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-ani-ai-featurestore-trainer
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-ani-ai-trainer
      taskRef:
        name: buildah-heavy
      params:
        - name: IMAGE
          value: quay.io/autonomousnetworkintelligence/ani-ai-featurestore-trainer:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: ai/featurestore/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: build-ani-incident-release
      retries: 1
      timeout: 45m0s
      runAfter:
        - build-ani-ai-featurestore-trainer
      taskRef:
        name: buildah-lite
      params:
        - name: IMAGE
          value: quay.io/autonomousnetworkintelligence/ani-incident-release:latest
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: incident-release/Containerfile
      workspaces:
        - name: source
          workspace: source
    - name: publish-sipp-runner-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-sipp-runner.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/sipp-runner
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-feature-gateway-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-feature-gateway.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/feature-gateway
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-anomaly-service-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-anomaly-service.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/anomaly-service
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-rca-service-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-rca-service.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/rca-service
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-demo-ui-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-demo-ui.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/demo-ui
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-control-plane-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-control-plane.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/control-plane
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-ani-ai-trainer-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-ani-ai-trainer.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/ani-ai-trainer
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-ani-ai-featurestore-trainer-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-ani-ai-featurestore-trainer.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/ani-ai-featurestore-trainer
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
    - name: publish-ani-incident-release-to-quay
      retries: 1
      timeout: 20m0s
      runAfter:
        - build-ani-incident-release
      when:
        - input: "$(params.publish-to-quay)"
          operator: in
          values: ["true"]
      taskRef:
        name: publish-image-if-authenticated
      params:
        - name: SOURCE_IMAGE
          value: $(tasks.build-ani-incident-release.results.IMAGE_URL)
        - name: DEST_IMAGE_REPO
          value: quay.io/$(params.quay-organization)/ani-incident-release
        - name: IMAGE_TAG
          value: $(params.quay-image-tag)
        - name: FALLBACK_IMAGE_TAG
          value: $(tasks.clone.results.COMMIT)
        - name: PUBLISH_ENABLED
          value: $(params.publish-to-quay)
        - name: PROMOTE_LATEST
          value: $(params.quay-promote-latest)
