apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitops-operator-group.yaml
  - gitops-operator-subscription.yaml
  - bootstrap-rbac.yaml
  - bootstrap-manifests-configmap.yaml
  - bootstrap-job.yaml
