apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ims-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: ims-demo
  source:
    path: deploy/gitops/operators
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitadmin/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    targetRevision: refactor/namespace-argo-split
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
