apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespaces
  - ../../base/ims
  - ../../base/traffic
  - ../../base/milvus
  - ../../base/minio
  - ../../base/platform
  - ../../base/serving
  - ../../base/observability
  - ../../base/pipelines
patches:
  - path: sandbox-resources.yaml
images:
  - name: ims-node
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/ims-node
    newTag: latest
  - name: sipp-runner
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/sipp-runner
    newTag: latest
  - name: control-plane
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/control-plane
    newTag: latest
  - name: feature-gateway
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/feature-gateway
    newTag: latest
  - name: anomaly-service
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/anomaly-service
    newTag: latest
  - name: rca-service
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/rca-service
    newTag: latest
  - name: demo-ui
    newName: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/demo-ui
    newTag: latest
