apiVersion: v1
kind: Namespace
metadata:
  name: ims-demo-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-applications

