apiVersion: v1
kind: LimitRange
metadata:
  name: ims-demo-default-resources
  namespace: ims-demo-lab
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
