apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ani-sipp
labels:
  - pairs:
      app.kubernetes.io/part-of: sipp-backfill-100k
    includeTemplates: true
resources:
  - jobs.yaml
