{{- if and .Values.rbac.enable .Values.mlflow.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kagenti-mlflow-integration-{{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controllerManager.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlflow-operator-mlflow-integration
{{- end -}}
