apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kagenti-manager-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agentcards
  - agentruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agentcards/finalizers
  - agentruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agentcards/status
  - agentruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/finalizers
  verbs:
  - update
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datasciencecluster.opendatahub.io
  resources:
  - datascienceclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlflow.opendatahub.io
  resources:
  - mlflows
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - mlflow.kubeflow.org
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - networks
  - zerotrustworkloadidentitymanagers
  verbs:
  - get
  - list
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
- apiGroups:
  - operator.tekton.dev
  resources:
  - tektonconfigs
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  resourceNames:
  - mlflow-operator-mlflow-integration
  - mlflow-operator-mlflow-edit
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - update
  - watch
