Identity = "ims-pcscf.ims-demo-lab.svc.cluster.local";                                                                                                                                              
Realm = "ims-demo-lab.svc.cluster.local";
Port = 3866;
SecPort = 0;
No_SCTP;
#NoRelay;

ConnectPeer = "ims-hss.ims-demo-lab.svc.cluster.local" {
  No_TLS;
  port = 3868;
};
