- op: replace
  path: /spec/tasks/1/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-sipp/sipp-runner:latest
- op: replace
  path: /spec/tasks/2/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-runtime/feature-gateway:latest
- op: replace
  path: /spec/tasks/3/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-runtime/anomaly-service:latest
- op: replace
  path: /spec/tasks/4/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-runtime/rca-service:latest
- op: replace
  path: /spec/tasks/5/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-runtime/demo-ui:latest
- op: replace
  path: /spec/tasks/6/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-runtime/control-plane:latest
- op: replace
  path: /spec/tasks/7/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-datascience/ani-ai-trainer:latest
- op: replace
  path: /spec/tasks/8/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-datascience/ani-ai-featurestore-trainer:latest
- op: replace
  path: /spec/tasks/9/params/0/value
  value: image-registry.openshift-image-registry.svc:5000/ani-datascience/ani-incident-release:latest
