apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-plane-read-aap-controller-password
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["aap-controller-admin-password", "aap-eda-admin-password"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    resourceNames: ["aap-controller"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-plane-read-aap-controller-password
subjects:
  - kind: ServiceAccount
    name: control-plane
    namespace: ani-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-plane-read-aap-controller-password
