apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: aap
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
