apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ims-sipp
resources:
  - ims-platform-config.yaml
  - ../../../base/traffic
images:
  - name: image-registry.openshift-image-registry.svc:5000/ims-demo-lab/sipp-runner
    newName: image-registry.openshift-image-registry.svc:5000/ims-sipp/sipp-runner
    newTag: latest
