apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - builds
  - ims
  - traffic
  - kafka
  - milvus
  - minio
  - platform
  - observability
  - rhoai
  - kfp
  - serving
  - pipelines
