apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ims-platform-build-
  namespace: ims-tekton
spec:
  pipelineRef:
    name: ims-platform-container-build
  params:
    - name: git-url
      value: http://gitea-http.gitea.svc.cluster.local:3000/gitadmin/IMS-Anomaly-Detection-with-Red-Hat-OpenShift-AI.git
    - name: git-revision
      value: main
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 4h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
